### PR TITLE
Minor enhancements to the build process

### PR DESCRIPTION
**Pull request by nulltoken**
As discussed with @davidknezic below a first proposal to slightly enhance an already amazing product.

This PR contains incremental changes.
 - The first one allows developers working on platform with different case sensitivity settings to get their files automatically normalized to LF line endings
 - The following ones plug eslint (with very basic code check rules) and [nsp](nsp) in
 - Final one leverages those additions as part of the build

I'm not done yet with it (I've got few more things to propose). As such, this is only a WIP PR, not ready to be merged in, in order to start the discussion.

Feedback is __very__ welcome :wink:

 [nsp]: https://nodesecurity.io/

### CODE REVIEW

**Comment by nulltoken** [comment]
Wow! Travis seems happy with that first chunk! :tada:

**Comment by nulltoken** [comment]
Added some more thingies:

 - Analysis of dependencies for know vulns
 - Ensure proper support of Node 8

**Comment by nulltoken** [comment]
Ok. No longer a WIP.

Ready for review.

**Review by sventschui — APPROVED** [review]

**Comment by nulltoken** [comment]
@sventschui Thanks for the approval. :purple_heart:

What would be the next steps to follow in order to see this merged?

**Comment by sventschui** [comment]
Let me get back from holidays :) Quite busy diving these days 🦈 🐢. Will release this stuff once I get home (approx. in a week). Maybe @davidknezic will release it sooner

**Comment by nulltoken** [comment]
>Let me get back from holidays :)

@sventschui Oh! No problem. Enjoy!

**Comment by nulltoken** [comment]
@sventschui 😍

**Comment by sventschui** [comment]
I won't do a release since these are only cosmetics. Therefore I could have merged this one sooner. Sorry for that. Was in holiday mode :D

**Pull request merged**
