### PR TITLE
Make plugin compatible with metalsmith cli

### PR DESCRIPTION
**Pull request by timohofmeijer**
I quickly made it compatible with the mailsmith cli and changed the README. I did break the API though, and I didn't run the tests nor tested the js API. Perhaps you can review my changes and do a major version bump if you approve. Meanwhile I’ll simply run my fork. Thanks!

### CODE REVIEW

**Comment by davidknezic** [comment]
Thanks for your contribution @timohofmeijer! :+1: 

We should definitely merge this and bump the version. Will review and test during this week.

**Comment by timohofmeijer** [comment]
I’ll fix some mistakes I made in the readme and test the JS API version. Aiming for tonight :smile:.

**Comment by davidknezic** [comment]
Fixed the tests and merged. Thank you very much @timohofmeijer!

This will be available in version `4.0.0`.

**Comment by sventschui** [comment]
It is now available as `4.0.0` on npm

**Comment by timohofmeijer** [comment]
:+1:

**Pull request merged**
