### PR TITLE
resolve absolute paths so things like postcss-import can work

### PR DESCRIPTION
**Pull request by juliekoubova**

### CODE REVIEW

**Comment by davidknezic** [comment]
Thank you for your contribution @juliekoubova! I'll make a new release on npm right away.

**Comment by juliekoubova** [comment]
thank you! :heart:

**Comment by davidknezic** [comment]
The publishing to npmjs might actually take a while. I've just realized I've no rights to publish to this package. Expect it until tomorrow at latest.

**Comment by sventschui** [comment]
Just pushed this change with `3.1.1` to npm. It is also included in `4.0.0`.

**Pull request merged**
